name: 'publish'

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Get version from package.json (Bash)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          VERSION=$(node -p 'require("./package.json").version')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get version from package.json (PowerShell)
        if: runner.os == 'Windows'
        id: get_version_ps
        shell: pwsh
        run: |
          $version = node -p "require('./package.json').version"
          Add-Content -Path $env:GITHUB_ENV -Value "VERSION=$version"

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          NO_STRIP: true
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURIY_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURIY_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: latest
          releaseName: 'Gov-Smart Signing Tool v${{ env.VERSION }}'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          includeUpdaterJson: true
          args: ${{ matrix.args }}
